default:
    image: node:17.2.0
    before_script:
        - yarn install

stages:
    - format
    - lint
    - build
    - deploy

format:
    stage: format
    script:
        - yarn fcheck

lint:
    stage: lint
    script:
        - yarn lint
    needs: ["format"]

build:
    stage: build
    script:
        - yarn build
    artifacts:
        paths:
            - dist/*
    needs: ["test"]

deploy:
    stage: deploy
    script:
        - yarn publish --new-version unstable-$CI_PIPELINE_ID
